# Generated by Django 3.2.13 on 2022-07-11 06:14

import accueil.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('passe', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=accueil.models.renommage)),
                ('insert', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_c', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nif', models.IntegerField()),
                ('adresse', models.CharField(max_length=150)),
                ('mrc', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=accueil.models.renommage)),
                ('passe', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('numero_tel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_p', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('prix', models.FloatField(max_length=11)),
                ('image', models.ImageField(upload_to=accueil.models.renommage)),
                ('description', models.CharField(max_length=255)),
                ('mu', models.CharField(max_length=100)),
                ('dp', models.DateTimeField()),
                ('marque', models.CharField(max_length=50)),
                ('fabriquant', models.CharField(max_length=100)),
                ('made_in', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=2)),
                ('vue', models.IntegerField()),
                ('categorie_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.categorieproduit')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('duree', models.IntegerField(default=30)),
                ('tarif', models.FloatField(default=0.0, max_length=21)),
                ('contact', models.CharField(max_length=100)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solliciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consommateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.consommateur')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.typeservice')),
            ],
        ),
        migrations.CreateModel(
            name='Resrevation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.consommateur')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.livreur')),
                ('payement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.payement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.ville')),
            ],
        ),
        migrations.CreateModel(
            name='ModeDePayementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.fournisseur')),
                ('mode_payement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.payement')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(max_length=2048)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de Publication')),
                ('consommateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.consommateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Administrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.administrateur')),
                ('publicite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.publicite')),
            ],
        ),
    ]
