# Generated by Django 3.2.13 on 2022-07-11 07:27

import accueil.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=accueil.models.renommage),
            preserve_default=False,
        ),
    ]
