# Generated by Django 3.2.13 on 2022-07-11 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_publicite_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieproduit',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='mk_icon_categorie/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='photo',
            field=models.ImageField(upload_to='mk_administrateur/'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='logo',
            field=models.ImageField(upload_to='mk_fournisseur/'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='mrc',
            field=models.CharField(choices=[('SMS', 'Message'), ('CALL', 'Appel'), ('MAIL', 'E-Mail')], max_length=30, verbose_name='Mode de reception commande'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nif',
            field=models.IntegerField(verbose_name="Numero d'Identification Fiscal"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dp',
            field=models.DateTimeField(verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='mk_produits/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='mu',
            field=models.CharField(max_length=100, verbose_name="Mode d'Utilisation"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pp',
            field=models.CharField(max_length=2, verbose_name='Priorité de présentation'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='nom_entreprise',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='photo',
            field=models.ImageField(upload_to='mk_pubs/'),
        ),
    ]
