# Generated by Django 4.0 on 2022-07-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_auto_20220712_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommateur',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consommateur',
            name='login',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consommateur',
            name='password',
            field=models.CharField(default='y', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicite',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
